name: '[fox-java] Publish package to the Maven Central Repository'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: 'master'
        
      - name: '[fox-java] Set up Java for publishing to Maven Central Repository'
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Publish to the Maven Central Repository
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_TOKEN }}
